CREATE TABLE IF NOT EXISTS "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "tg_id" int UNIQUE,
  "tg_nickname" varchar UNIQUE,
  "word_of_day_subscribed" bool DEFAULT true,
  "ctime" timestamp NOT NULL DEFAULT (now()),
  "utime" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "words" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "word" text NOT NULL,
  "meaning" text NOT NULL DEFAULT (''::text),
  "level" varchar(10),
  "ctime" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "word_translations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "word_id" int NOT NULL,
  "language" text NOT NULL,
  "translation" text NOT NULL DEFAULT (''::text),
  "ctime" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "user_words" (
  "user_id" int NOT NULL,
  "word_id" int NOT NULL,
  "learned" bool NOT NULL DEFAULT false,
  "list_added" bool NOT NULL DEFAULT false,
  "ctime" timestamp NOT NULL DEFAULT (now()),
  "utime" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("user_id", "word_id")
);

CREATE TABLE IF NOT EXISTS "word_examples" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "word_id" int NOT NULL,
  "example_sentece" text,
  "ctime" timestamp NOT NULL DEFAULT (now()),
  "utime" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "word_example_translations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "word_example_id" int NOT NULL,
  "language" text NOT NULL,
  "translation" text NOT NULL DEFAULT (''::text),
  "ctime" timestamp NOT NULL DEFAULT (now())
);

CREATE INDEX ON "words" ("level");

CREATE INDEX ON "word_translations" ("word_id");

CREATE INDEX ON "user_words" ("user_id", "learned");

CREATE INDEX ON "word_examples" ("word_id");

CREATE INDEX ON "word_example_translations" ("word_example_id");

ALTER TABLE "word_translations" ADD FOREIGN KEY ("word_id") REFERENCES "words" ("id");

ALTER TABLE "user_words" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_words" ADD FOREIGN KEY ("word_id") REFERENCES "words" ("id");

ALTER TABLE "word_examples" ADD FOREIGN KEY ("word_id") REFERENCES "words" ("id");

ALTER TABLE "word_example_translations" ADD FOREIGN KEY ("word_example_id") REFERENCES "word_examples" ("id");
