

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "tg_id" int UNIQUE,
  "tg_nickname" varchar UNIQUE,
  "word_of_day_subscribed" bool DEFAULT true,
  "ctime" timestamp NOT NULL DEFAULT (now()),
  "utime" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "words" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "word" text NOT NULL,
  "meaning" text NOT NULL default '',
  "translate_ru" text not null default '',
  "level" text not null default '',
  "ctime" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "user_words" (
  "user_id" int NOT NULL,
  "word_id" int NOT NULL,
  "learned" bool NOT NULL DEFAULT false,
  "list_added" bool NOT NULL DEFAULT false,
  "ctime" timestamp NOT NULL DEFAULT (now()),
  "utime" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("user_id", "word_id")
);

CREATE TABLE "word_examples" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "word_id" int NOT NULL,
  "example_sentece" text,
  "translate_ru" text,
  "ctime" timestamp NOT NULL DEFAULT (now()),
  "utime" timestamp NOT NULL DEFAULT (now())
);

CREATE INDEX ON "words" ("level");

CREATE INDEX ON "user_words" ("user_id", "learned");

CREATE INDEX ON "word_examples" ("word_id");

ALTER TABLE "user_words" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_words" ADD FOREIGN KEY ("word_id") REFERENCES "words" ("id");

ALTER TABLE "word_examples" ADD FOREIGN KEY ("word_id") REFERENCES "words" ("id");
